--관리자 계정
CREATE USER semi IDENTIFIED BY semi;
GRANT CONNECT,RESOURCE TO semi;

--semi계정
CREATE TABLE MEMBER(
    IDX NUMBER CONSTRAINT MEMBER_IDX_PK PRIMARY KEY,
    MEMBER_ID VARCHAR2(30) CONSTRAINT MEMBER_ID_UQNN UNIQUE NOT NULL,
    MEMBER_PW VARCHAR2(30) CONSTRAINT MEMBER_PW_NN NOT NULL,
    MEMBER_NAME VARCHAR2(30) CONSTRAINT MEMBER_NAME_NN NOT NULL,
    PHONE VARCHAR2(30),
    ADDRESS VARCHAR2(30),
    BIRTH_DATE DATE,
    ENROLL_DATE DATE,
    DOTORI NUMBER DEFAULT(0)
);

CREATE SEQUENCE SEQ_MEMBER
NOCYCLE
NOCACHE;

CREATE TABLE BOARD(
    IDX NUMBER CONSTRAINT BOARD_IDX_PK PRIMARY KEY,
    WRITER NUMBER,
    TITLE VARCHAR2(100) CONSTRAINT BOARD_TITLE_NN NOT NULL,
    CONTENTS VARCHAR2(1000),
    ENROLL_DATE DATE,
    LAST_UPDATE DATE,
    CONSTRAINT CONS_WRITER_REF FOREIGN KEY(WRITER) REFERENCES MEMBER(IDX) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_BOARD
NOCYCLE
NOCACHE;